#!/usr/bin/env bash

IMAGE_NAME="architecture-builder-bff"
IMAGE_VER="1.0.0"

if [[ -z "${IMAGE_NAME}" ]] || [[ -z "${IMAGE_VER}" ]]; then
   echo "Required input is missing"
   echo "Usage: build.sh IMAGE_NAME IMAGE_VER"
   exit 1
fi

echo "Building ${IMAGE_NAME}:${IMAGE_VER}"

docker run -d -p 3000:3000 --env PORT=3000  ${IMAGE_NAME}:${IMAGE_VER}

#docker run -v ~/projects/gsi/admin/gsi-lab-proxy:/etc/nginx/conf.d -e PORT=80 -e APP_ROOT=sandbox nginx:alpine
